### PR TITLE
Update install.sh for installation with no errors - (Solves - #109)

### LINKED ISSUE #109: This installs susi_desktop client without any errors
#### Describe the bug
This will install susi_desktop client errors in the Linux systems without any error
Due to confusion between the `development` and `master` branch in susi_linux repo, had made some changes I am reverting it now and this will install the `susi_linux` desktop client without any error. 
I have tested it now, it is installing the client without any errors

#### Expected behavior
Installation of the susi-desktop client without any errors

#### Desktop (please complete the following information):
 - OS:  Ubuntu 18.10
 - Browser Firefox

### PR DESCRIPTION
**Pull request by pranav1698**
Fixes #109 

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [ ] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

### CODE REVIEW

**Comment by norbusan** [comment]
Yes, the installer uses the same branches (master/master and dev/dev) when installing. It is probably better to check for **both** locations (I did this first in the dev branch before switching all sub-projects). The reason is that triggered builds (commits to susi_linux and susi_python trigger a ci test on susi_installer) will use the development branch. But so what, for now let it be as is.

**Comment by norbusan** [comment]
BTW, I think if you use (Closes: #109) it will be closed automatically, but I might be wrong ;-)

**Comment by pranav1698** [comment]
Fixes keyword also do the same work: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by pranav1698** [comment]
Clearly it is not working, I will try closes next time

**Comment by norbusan** [comment]
@pranav1698 I think it is the dash "-" between "Solves" and the bug number.

**Pull request merged**
