### PR TITLE
Add a remote access webpage to the soundserver[WIP]

### LINKED ISSUE #36: Add a remote access webpage to the soundserver
#### Is your feature request related to a problem? Please describe.
Add a remote access webpage to the soundserver.py
- Make a webpage available on the local network.
- This webpage should enable anyone on the same network(with authentication if needed) to control the smart speaker.
- Add audio control features to it such as play, pause and volume control.
- Add basic authentication.

The SUSI android app can use the webpage/endpoints to control the smart speaker

I'm working on this.

### PR DESCRIPTION
**Pull request by alok760**
Fixes #36

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
- Add a webpage to soundserver available on the local network.
- This webpage enables anyone on the same network(with authentication if needed) to control the smart speaker.
- Add audio control features - pause, next, previous, resume, stop, shuffle

### CODE REVIEW

**Comment by alok760** [comment]
Work in progress 
Things I'll be adding in this PR
- Work on UI/ placement and grouping of buttons
- Add authentication 
- Add play youtube video from URL feature

**Comment by norbusan** [comment]
I took a look, and it is in principle nice, but it doesn't work and will not in this way as we expect to do.
We planned to block access to the soundserver PUT routes (direct adjustments) and allow only from localhost. But with this page when pressing a button, the requests are again send from the remote host (of course).

I added a pre request filter that rejects all remote non-GET requests:
```
@app.before_request
def limit_access():
    if request.remote_addr != '127.0.0.1' and request.method != 'GET':
        abort(403) # Forbidden
```

With that I can access the web page `index.html` from remote, don't do direct calls to the PUT end points, but I also cannot push any button:
```
192.168.1.53 - - [19/Jun/2019 10:10:06] "GET / HTTP/1.1" 200 -
192.168.1.53 - - [19/Jun/2019 10:10:09] "POST /stop HTTP/1.1" 403 -
192.168.1.53 - - [19/Jun/2019 10:10:19] "POST /pause HTTP/1.1" 403 -
```
The last lines are coming from pushing buttons on my mobile while the server runs on the desktop.

I am not sure how this can be solved, I have some ideas, but since I never touched Flask before I really don't know
- context objects seem to be related
- programmatically ad some secret that is added to the second call which makes the server not abort

Do you have any suggestions?

**Comment by norbusan** [comment]
Maybe we just ignore all that and leave the web page (with improvements for volume etc) as is, and forget about restrictions etc.

**Comment by alok760** [comment]
@norbusan It should work fine after adding authentication.
I'll block all the routes except login if the user is not authenticated.
and make the server available on the local network.

**Comment by alok760** [comment]
@norbusan Thanks for the pointers, I'll work more and update you.

**Comment by mariobehling** [comment]
I think this is a good start. We could add restrictions later. Let's get the basics working.

**Comment by alok760** [comment]
Here's the final UI
image

**Comment by norbusan** [comment]
Thanks

**Pull request merged**
