### PR TITLE
grey out all sound related options in control template

### LINKED ISSUE #76: Gray out the sound related parts in the control template
- The use of sound related endpoints in the control server causes susi_linux to crash and thus such endpoints are disabled temporarily - https://github.com/fossasia/susi_installer/commit/53bb57f6a314d4254b5d61a33d0baf6927b5f1ed
- The options in the control template which uses these endpoints should be grayed out.

### PR DESCRIPTION
**Pull request by alok760**
Fixes #76

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [ ] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

- Greyed-out all the options in the control server as all options were using disabled endpoints

### CODE REVIEW

**Comment by norbusan** [comment]
Hi @alok760 
thanks! But please, it should not only be greyed out, but also clicking the buttons etc should be disabled, and maybe some message "Coming soon" ...

**Comment by norbusan** [comment]
In addition, the change of the template does only apply to the "Smart Spekaer Control" card, but **not** to the others. Please update that.

I would generally suggest that we simply comment the code, but then one has to be careful with the layout and which parts.

I looked into the template and the structure is a huge chaos there, a few too many nestings for my feeling.

Please look into that.

**Comment by alok760** [comment]
@norbusan the overlay disables clicking on everything

image

**Comment by alok760** [comment]
Also currently, every part of the page is related to sound, so I had to disable the whole page, is there anything which should be kept?

**Comment by norbusan** [comment]
Ah, umhh, yes. then the only thing that remains is the login stuff down on the right.
We could disable this page completely for now, since there is nothing that can be done,right?

Sorry for the mis-reading of the code change,I didn't see why the buttons would be disabled.

WDYT about disabling this page completely?

**Comment by norbusan** [comment]
Merged for now, more adjustments later. Thanks

**Pull request merged**
