### PR TITLE
susi-config program: introduction and usage in the server

### PR DESCRIPTION
**Pull request by norbusan**
This PR introduces a program `susi-config` which is responsible for
setting all kind of parameters in the `config.json` file, as well as logging
into the susi.ai services.

It replaces `susi_linux` scripts `authentication`, `config_generator`, and `susi_login`.

The flask AP server is adjusted to use the new script.

All calls are done as user `pi` instead of root to make sure that `config.json` always remains owned by `pi`.

Tested on the RPi with a test image.

### CODE REVIEW

**Comment by norbusan** [comment]
Merged

**Comment by hongquan** [comment]
Any reason why you don't design it as a lib, so that other part of SUSI just import and call its functions, instead of call the command `sudo susi-config`?

**Comment by norbusan** [comment]
Thanks @hongquan hmmm, I didn't see the need for that, but yes, you mean adding
```
if __name__ == '__main__':
    do the stuff that is now on the outer level
```
I would put the command line handling into a separate function and call that one if it is main.

Do you think other changes are necessary, too?

**Comment by hongquan** [comment]
@norbusan Yes, do like that.

No other things to do (I haven't thought that).

**Comment by norbusan** [comment]
Done that and commited. If you have comments @hongquan please let me know

**Pull request closed without merging**
