### PR TITLE
Add feature to play songs from a particular artist from the USB device [WIP]

### LINKED ISSUE #28: Add support for more USB media discovery skills
#### Is your feature request related to a problem? Please describe.
- Add support for more USB media discovery skills such as 
    - SUSI, play rock music from USB (a specific genre)
    - SUSI, play all maroon5 songs from USB (a specific artist)
- This Issue requires fetching metadata of all audio files in the USB and create skills on the fly

### PR DESCRIPTION
**Pull request by alok760**
Fixes #28

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
These changes make on the fly skill grouping songs from different artists in the USB drive 
The Skill is **"Susi, play 'artist_name' from USB"**

example of skill created
```
play audio
!console:Playing audio from your usb device
{"actions":[
{"type":"audio_play", "identifier_type":"url", "identifier":"file:///media/usb0/owlcity - fireflies.mp3;file:///media/usb0/01 Waiting For The End.mp3;file:///media/usb0/02 Foreword.mp3"}
]}
eol

play owl city from usb
!console:Playing audio from your usb device
{"actions":[
{"type":"audio_play", "identifier_type":"url", "identifier":"file:///media/usb0/owlcity - fireflies.mp3"}
]}
eol

play Linkin Park from usb
!console:Playing audio from your usb device
{"actions":[
{"type":"audio_play", "identifier_type":"url", "identifier":"file:///media/usb0/01 Waiting For The End.mp3;file:///media/usb0/02 Foreword.mp3"}
]}
eol
```

### CODE REVIEW

**Comment by norbusan** [comment]
Why do you use `eye3d`? It only supports mp3 data. Since we search for flac/ogg/mp3/wav files, we should try to support as many of them as possible. I searched a bit and from my reading I would suggested `pytaglib` https://pypi.org/project/pytaglib/ for reading tags from all supported files.
I have pushed builds for arm/python3.5 (raspi) and amd64/python3.7 to fossasia's gemfury.

This library can parse all the other file formats, too.

**Comment by norbusan** [comment]
mutagen https://mutagen.readthedocs.io/en/latest/ would be another alternative that needs only plain Python without external libs

**Comment by stealthanthrax** [comment]
Yes, mutagen is much simpler to implement as well!
> mutagen https://mutagen.readthedocs.io/en/latest/ would be another alternative that needs only plain Python without external libs

**Comment by norbusan** [comment]
Should I push binary builds of mutagen to fossasia's gemfury?

**Comment by alok760** [comment]
@norbusan @stealthanthrax I have updated the code to use mutagen and handle all the formats, kindly take a look

**Comment by hongquan** [comment]
> Should I push binary builds of mutagen to fossasia's gemfury?

@norbusan Yes.

**Comment by norbusan** [comment]
@hongquan 

> > Should I push binary builds of mutagen to fossasia's gemfury?
> 
> @norbusan Yes.

I realized this is not necessary, since mutagen is pure python code and pip install will pull a fine version already. No need to build anything.

**Comment by norbusan** [comment]
Thanks

**Pull request merged**
